import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { createDefaultRegistry, type SupportedFormat } from "@verbatra/sdk";
import { describe, expect, it } from "vitest";
import { FORMAT_SAMPLES, sampleLines, splitOnPlaceholder } from "./format-samples";
import {
  FORMAT_SAMPLE_SPECS,
  memoryAdapterFs,
  SAMPLE_SOURCE,
  SAMPLE_SOURCE_LOCALE,
  sampleEntries,
} from "./format-samples-seed.mjs";
import { SUPPORTED_FORMAT_IDS } from "./landing-facts";
import { SHOWCASE_SOURCE } from "./showcase-seed";
import { STACK_FRAMEWORKS } from "./stack-formats";
import { STACKS } from "./stacks";

function sourceOf(relative: string): string {
  return readFileSync(fileURLToPath(new URL(relative, import.meta.url)), "utf8");
}

async function reread(format: SupportedFormat) {
  const sample = FORMAT_SAMPLES[format];
  const files = new Map([[sample.file, sample.text]]);
  const registry = createDefaultRegistry(memoryAdapterFs(files));
  const resolution = registry.resolve(sample.file, { format });
  if (resolution.status !== "resolved") throw new Error(`no adapter for ${format}`);
  const { resource } = await resolution.adapter.read(sample.file, SAMPLE_SOURCE_LOCALE);
  return [...resource.entries.values()];
}

describe("format samples", () => {
  it("holds exactly one sample per supported format, in registry order", () => {
    expect(Object.keys(FORMAT_SAMPLES)).toEqual([...SUPPORTED_FORMAT_IDS]);
    expect(Object.keys(FORMAT_SAMPLE_SPECS)).toEqual([...SUPPORTED_FORMAT_IDS]);
  });

  it("seeds every sample with the showcase's English source strings", () => {
    for (const { path, value } of SAMPLE_SOURCE) {
      const [group, leaf] = path;
      const branch = SHOWCASE_SOURCE[group];
      expect(typeof branch === "object" ? branch[leaf] : undefined).toBe(value);
    }
    expect(SAMPLE_SOURCE).toHaveLength(Object.values(SHOWCASE_SOURCE).flatMap(Object.keys).length);
  });

  it.each(SUPPORTED_FORMAT_IDS)(
    "%s re-parses through the real adapter to the seed",
    async (format) => {
      const entries = await reread(format);
      expect(entries.map(({ key, value }) => ({ key, value }))).toEqual(sampleEntries(format));
    },
  );

  it.each(SUPPORTED_FORMAT_IDS)(
    "%s carries its own placeholder, which the adapter reads back as one",
    async (format) => {
      const { placeholder, text } = FORMAT_SAMPLES[format];
      expect(placeholder).toBe(FORMAT_SAMPLE_SPECS[format].placeholder);
      expect(text).toContain(placeholder);
      const [total] = await reread(format);
      expect(total?.placeholders).toEqual([placeholder]);
    },
  );

  it("splits a line around its placeholder without losing a character", () => {
    expect(splitOnPlaceholder('  "total": "Total: %1$s",', "%1$s")).toEqual([
      '  "total": "Total: ',
      "%1$s",
      '",',
    ]);
    expect(splitOnPlaceholder("Sign in", "{0}")).toEqual(["Sign in"]);
    for (const format of SUPPORTED_FORMAT_IDS) {
      const sample = FORMAT_SAMPLES[format];
      expect(sampleLines(sample).join("\n")).toBe(sample.text.replace(/\n$/, ""));
      for (const line of sampleLines(sample)) {
        expect(splitOnPlaceholder(line, sample.placeholder).join("")).toBe(line);
      }
    }
  });

  it("is generated by a prebuild script and never imports the sdk at runtime", () => {
    const pkg = JSON.parse(sourceOf("../package.json")) as { scripts: Record<string, string> };
    for (const script of ["dev", "build", "typecheck", "test"]) {
      expect(pkg.scripts[script], script).toContain("node scripts/sync-format-samples.mjs");
    }
    expect(sourceOf("../.gitignore")).toContain("lib/format-samples.generated.json");
    const script = sourceOf("../scripts/sync-format-samples.mjs");
    expect(script).toContain('import { createDefaultRegistry } from "@verbatra/sdk";');
    expect(script).not.toContain("@verbatra/format-adapters");
    for (const file of [
      "./format-samples.ts",
      "./format-samples-seed.mjs",
      "./stack-formats.ts",
      "../components/landing/formats.tsx",
      "../components/landing/format-switch.tsx",
    ]) {
      const source = sourceOf(file);
      expect(source, file).not.toMatch(
        /^import (?!type )[^;]*from "@verbatra\/(sdk|format-adapters)"/m,
      );
    }
    const docsPackage = JSON.parse(sourceOf("../package.json")) as {
      dependencies: Record<string, string>;
      devDependencies: Record<string, string>;
    };
    expect({ ...docsPackage.dependencies, ...docsPackage.devDependencies }).not.toHaveProperty(
      "@verbatra/format-adapters",
    );
  });
});

describe("stack frameworks", () => {
  it("selects the format each documented stack quickstart uses", () => {
    const byName = new Map<string, SupportedFormat>(
      STACK_FRAMEWORKS.map((framework) => [framework.key, framework.format]),
    );
    const aliases: Record<string, string> = { nextjs: "next" };
    for (const stack of Object.values(STACKS)) {
      const key = aliases[stack.id] ?? stack.id;
      expect(byName.get(key), stack.id).toBe(stack.format);
    }
  });

  it("names only supported formats", () => {
    for (const framework of STACK_FRAMEWORKS) {
      expect(SUPPORTED_FORMAT_IDS).toContain(framework.format);
    }
  });
});
