import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { AdapterRegistry } from "@verbatra/format-adapters";
import { describe, expect, it } from "vitest";
import { SdkError } from "../errors.js";
import { baseConfig, makeTempDir, readTextFile, writeJsonFile } from "../test-support.js";
import { DEFAULT_TYPES_PATH, generateTypes } from "./generate-types.js";

async function seed(catalog: Record<string, unknown>): Promise<string> {
  const dir = await makeTempDir();
  await mkdir(join(dir, "locales"), { recursive: true });
  await writeJsonFile(join(dir, "locales", "en.json"), catalog);
  return dir;
}

function membersOf(declaration: string): readonly string[] {
  const body = /export interface VerbatraMessages \{\n([\s\S]*?)\n\}/.exec(declaration);
  return body?.[1] === undefined ? [] : body[1].split("\n");
}

async function declarationIn(dir: string): Promise<string> {
  return readTextFile(join(dir, DEFAULT_TYPES_PATH));
}

describe("generateTypes: generating the declaration", () => {
  it("writes the declaration beside the project and reports what it declared", async () => {
    const dir = await seed({ title: "Verbatra", greeting: "Hello {{name}}" });

    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result).toMatchObject({
      path: join(dir, DEFAULT_TYPES_PATH),
      keys: 2,
      withArguments: 1,
      written: true,
      stale: true,
      check: false,
    });
    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "title": VerbatraNoArguments;',
      '  "greeting": { readonly "name": VerbatraArgument };',
    ]);
  });

  it("names the source catalog relative to the working directory, not as an absolute path", async () => {
    const dir = await seed({ title: "Verbatra" });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(await declarationIn(dir)).toContain(
      "// Generated by verbatra from locales/en.json (i18next-json).",
    );
    expect(await declarationIn(dir)).not.toContain(dir);
  });

  it("keeps the source document order rather than sorting the keys", async () => {
    const dir = await seed({ zebra: "Z", apple: "A", mango: "M" });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "zebra": VerbatraNoArguments;',
      '  "apple": VerbatraNoArguments;',
      '  "mango": VerbatraNoArguments;',
    ]);
  });

  it("produces byte-identical output on a second run over an unchanged catalog", async () => {
    const dir = await seed({ title: "Verbatra", greeting: "Hello {{name}}" });

    await generateTypes({ config: baseConfig(), cwd: dir });
    const first = await declarationIn(dir);
    const second = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(await declarationIn(dir)).toBe(first);
    expect(second).toMatchObject({ written: false, stale: false });
  });

  it("rewrites the file after the source catalog changes", async () => {
    const dir = await seed({ title: "Verbatra" });
    await generateTypes({ config: baseConfig(), cwd: dir });

    await writeJsonFile(join(dir, "locales", "en.json"), { title: "Verbatra", added: "New" });
    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result).toMatchObject({ written: true, stale: true, keys: 2 });
    expect(membersOf(await declarationIn(dir))).toContain('  "added": VerbatraNoArguments;');
  });

  it("writes to a nested output path, creating the directory it needs", async () => {
    const dir = await seed({ title: "Verbatra" });

    const result = await generateTypes({
      config: baseConfig(),
      cwd: dir,
      out: "src/generated/messages.d.ts",
    });

    expect(result.path).toBe(join(dir, "src", "generated", "messages.d.ts"));
    expect(await readTextFile(result.path)).toContain('"title": VerbatraNoArguments;');
  });
});

describe("generateTypes: keys the format spells in ways TypeScript does not", () => {
  it("emits every awkward key as a quoted member without corrupting the file", async () => {
    const dir = await seed({
      class: "reserved",
      "1st": "leading digit",
      "": "empty",
      'say "hi"': "quoted",
      "tab\tkey": "control character",
    });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "class": VerbatraNoArguments;',
      '  "1st": VerbatraNoArguments;',
      '  "": VerbatraNoArguments;',
      '  "say \\"hi\\"": VerbatraNoArguments;',
      '  "tab\\tkey": VerbatraNoArguments;',
    ]);
  });

  it("declares a nested path as the single dotted key the adapter flattened it to", async () => {
    const dir = await seed({ app: { nav: { home: "Home" } } });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(membersOf(await declarationIn(dir))).toEqual(['  "app.nav.home": VerbatraNoArguments;']);
  });

  it("keeps the adapter's escaping of a literal dot rather than re-splitting the key", async () => {
    const dir = await seed({ "a.b": "one leaf, not two" });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(membersOf(await declarationIn(dir))).toEqual(['  "a\\\\.b": VerbatraNoArguments;']);
  });

  it("keeps the adapter's escaping of a literal backslash", async () => {
    const dir = await seed({ "a\\b": "backslash" });

    await generateTypes({ config: baseConfig(), cwd: dir });

    expect(membersOf(await declarationIn(dir))).toEqual(['  "a\\\\\\\\b": VerbatraNoArguments;']);
  });
});

describe("generateTypes: what the read reported as unusable", () => {
  it("leaves out a leaf the adapter excluded and reports it instead", async () => {
    const dir = await seed({ title: "Verbatra", retries: 3 });

    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result.excluded).toEqual(["retries"]);
    expect(result.keys).toBe(1);
    expect(membersOf(await declarationIn(dir))).toEqual(['  "title": VerbatraNoArguments;']);
  });

  it("keeps a key whose message syntax is invalid but claims nothing about its arguments", async () => {
    const dir = await seed({ good: "Hello {name}", broken: "Hello {name" });

    const result = await generateTypes({
      config: baseConfig({ format: "next-intl-json" }),
      cwd: dir,
    });

    expect(result.unresolved).toEqual([{ key: "broken", reason: "invalid-message-syntax" }]);
    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "good": { readonly "name": VerbatraArgument };',
      '  "broken": VerbatraUnknownArguments;',
    ]);
  });
});

describe("generateTypes: plural keys", () => {
  it("declares each plural sibling separately and lists them as plural", async () => {
    const dir = await seed({
      title: "Verbatra",
      item_one: "{{count}} item",
      item_other: "{{count}} items",
    });

    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result.plural).toEqual(["item_one", "item_other"]);
    expect(await declarationIn(dir)).toContain(
      'export type VerbatraPluralMessageKey = "item_one" | "item_other";',
    );
    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "title": VerbatraNoArguments;',
      '  "item_one": { readonly "count": VerbatraArgument };',
      '  "item_other": { readonly "count": VerbatraArgument };',
    ]);
  });
});

describe("generateTypes: a format whose arguments are positional", () => {
  it("declares a tuple for a printf catalog rather than inventing names", async () => {
    const dir = await makeTempDir();
    await mkdir(join(dir, "locales"), { recursive: true });
    await writeFile(
      join(dir, "locales", "en.strings"),
      '"welcome" = "Hi %@, you have %d messages";\n',
      "utf8",
    );

    await generateTypes({
      config: baseConfig({
        format: "apple-strings",
        files: { pattern: "locales/{locale}.strings" },
      }),
      cwd: dir,
    });

    expect(membersOf(await declarationIn(dir))).toEqual([
      '  "welcome": readonly [VerbatraArgument, number];',
    ]);
  });
});

describe("generateTypes: the staleness check", () => {
  it("reports a freshly generated file as current and writes nothing", async () => {
    const dir = await seed({ title: "Verbatra" });
    await generateTypes({ config: baseConfig(), cwd: dir });
    const before = await declarationIn(dir);

    const result = await generateTypes({ config: baseConfig(), cwd: dir, check: true });

    expect(result).toMatchObject({ stale: false, written: false, check: true });
    expect(await declarationIn(dir)).toBe(before);
  });

  it("reports a file left behind by an older catalog as stale and still writes nothing", async () => {
    const dir = await seed({ title: "Verbatra" });
    await generateTypes({ config: baseConfig(), cwd: dir });
    const before = await declarationIn(dir);
    await writeJsonFile(join(dir, "locales", "en.json"), { title: "Verbatra", added: "New" });

    const result = await generateTypes({ config: baseConfig(), cwd: dir, check: true });

    expect(result).toMatchObject({ stale: true, written: false });
    expect(await declarationIn(dir)).toBe(before);
  });

  it("reports a missing file as stale and does not create it", async () => {
    const dir = await seed({ title: "Verbatra" });

    const result = await generateTypes({ config: baseConfig(), cwd: dir, check: true });

    expect(result).toMatchObject({ stale: true, written: false });
    await expect(declarationIn(dir)).rejects.toThrow();
  });

  it("reports a hand-edited file as stale", async () => {
    const dir = await seed({ title: "Verbatra" });
    await generateTypes({ config: baseConfig(), cwd: dir });
    await writeFile(join(dir, DEFAULT_TYPES_PATH), "export type Nonsense = never;\n", "utf8");

    expect(await generateTypes({ config: baseConfig(), cwd: dir, check: true })).toMatchObject({
      stale: true,
    });
  });
});

describe("generateTypes: refusals", () => {
  it("surfaces an unresolvable format as a structured error, not a raw one", async () => {
    const dir = await seed({ title: "Verbatra" });

    const failure = generateTypes(
      { config: baseConfig({ format: "custom:nowhere" }), cwd: dir },
      { adapterRegistry: new AdapterRegistry() },
    );

    await expect(failure).rejects.toThrow(SdkError);
    await expect(failure).rejects.toMatchObject({ code: "UNKNOWN_FORMAT" });
  });

  it("refuses an absolute output path", async () => {
    const dir = await seed({ title: "Verbatra" });

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: join(dir, "elsewhere.d.ts") }),
    ).rejects.toMatchObject({ code: "TYPES_OUTPUT_CONFLICT" });
  });

  it("refuses an output path that climbs out of the working directory", async () => {
    const dir = await seed({ title: "Verbatra" });

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "../escaped.d.ts" }),
    ).rejects.toMatchObject({ code: "TYPES_OUTPUT_CONFLICT" });
  });

  it("refuses to write the declaration over a configured locale file", async () => {
    const dir = await seed({ title: "Verbatra" });

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "locales/de.json" }),
    ).rejects.toMatchObject({ code: "TYPES_OUTPUT_CONFLICT" });
  });

  it("refuses an output path naming no file", async () => {
    const dir = await seed({ title: "Verbatra" });

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "   " }),
    ).rejects.toMatchObject({ code: "TYPES_OUTPUT_CONFLICT" });
  });

  it("reports a missing source catalog as a structured error", async () => {
    const dir = await makeTempDir();

    await expect(generateTypes({ config: baseConfig(), cwd: dir })).rejects.toMatchObject({
      code: "SOURCE_UNREADABLE",
    });
  });

  it("reports an unwritable output path as a structured error", async () => {
    const dir = await seed({ title: "Verbatra" });

    await expect(
      generateTypes(
        { config: baseConfig(), cwd: dir },
        {
          fs: {
            ...(await import("../fs.js")).defaultFs,
            writeFile: async (): Promise<void> => {
              throw new Error("read-only file system");
            },
          },
        },
      ),
    ).rejects.toMatchObject({ code: "TYPES_UNWRITABLE" });
  });
});
