import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { baseConfig, makeTempDir, readTextFile } from "../test-support.js";
import { DEFAULT_TYPES_PATH, generateTypes } from "./generate-types.js";

const run = promisify(execFile);

const TSC = join(dirname(dirname(import.meta.dirname)), "node_modules", ".bin", "tsc");

const TSCONFIG = {
  compilerOptions: {
    strict: true,
    noUncheckedIndexedAccess: true,
    exactOptionalPropertyTypes: true,
    target: "ES2022",
    module: "NodeNext",
    moduleResolution: "NodeNext",
    noEmit: true,
    skipLibCheck: false,
    types: [],
  },
  files: ["usage.ts"],
};

const USAGE = `import type { VerbatraMessageKey } from "./verbatra-types.js";

export const key: VerbatraMessageKey = "title";
`;

const TERMINATORS: readonly (readonly [string, string, string])[] = [
  ["a line feed", "\n", "\\n"],
  ["a carriage return", "\r", "\\r"],
  ["a line separator", "\u2028", "\\u2028"],
  ["a paragraph separator", "\u2029", "\\u2029"],
];

async function generateWith(marker: string): Promise<{ dir: string; declaration: string }> {
  const dir = await makeTempDir();
  const folder = `loc${marker}ales`;
  await mkdir(join(dir, folder), { recursive: true });
  await writeFile(join(dir, folder, "en.json"), '{\n  "title": "Verbatra"\n}\n', "utf8");
  const config = baseConfig({ files: { pattern: `${folder}/{locale}.json` } });
  await generateTypes({ config, cwd: dir });
  return { dir, declaration: await readTextFile(join(dir, DEFAULT_TYPES_PATH)) };
}

async function compile(declaration: string): Promise<string> {
  const dir = await makeTempDir();
  await writeFile(join(dir, "verbatra-types.d.ts"), declaration, "utf8");
  await writeFile(join(dir, "usage.ts"), USAGE, "utf8");
  await writeFile(join(dir, "tsconfig.json"), JSON.stringify(TSCONFIG, null, 2), "utf8");
  try {
    return (await run(TSC, ["-p", dir], { cwd: dir })).stdout;
  } catch (error) {
    const failure = error as { stdout?: string; stderr?: string };
    return `${failure.stdout ?? ""}${failure.stderr ?? ""}` || String(error);
  }
}

const BASELINE_LINES = 30;

describe("a line terminator in the configured source path", () => {
  it.each(TERMINATORS)("keeps the header on one line for %s", async (_label, marker, escaped) => {
    const { declaration } = await generateWith(marker);
    const [header, second] = declaration.split("\n");

    expect(header).toBe(
      `// Generated by verbatra from loc${escaped}ales/en.json (i18next-json). Do not edit by hand.`,
    );
    expect(second).toBe("// Re-run `verbatra types` after the source catalog changes.");
    expect(header).not.toContain(marker);
  });

  it.each(TERMINATORS)("adds no extra line to the file for %s", async (_label, marker) => {
    const clean = await generateWith("-");
    const { declaration } = await generateWith(marker);

    expect(declaration.split("\n")).toHaveLength(BASELINE_LINES);
    expect(clean.declaration.split("\n")).toHaveLength(BASELINE_LINES);
  });

  it.each(TERMINATORS)("still reports the raw path in the result for %s", async (_l, marker) => {
    const dir = await makeTempDir();
    const folder = `loc${marker}ales`;
    await mkdir(join(dir, folder), { recursive: true });
    await writeFile(join(dir, folder, "en.json"), '{\n  "title": "Verbatra"\n}\n', "utf8");

    const result = await generateTypes({
      config: baseConfig({ files: { pattern: `${folder}/{locale}.json` } }),
      cwd: dir,
    });

    expect(result.sourcePath.startsWith("loc")).toBe(true);
    expect(result.keys).toBe(1);
  });
});

describe("the escaped header still compiles, and check mode still sees the truth", () => {
  it.each(TERMINATORS)(
    "compiles the declaration produced from %s",
    async (_label, marker) => {
      const { declaration } = await generateWith(marker);

      expect(await compile(declaration)).toBe("");
    },
    180_000,
  );

  it("really ran tsc: an unescaped header breaks the same compilation", async () => {
    const { declaration } = await generateWith("\n");
    const broken = declaration.replace("\\n", "\n");

    const output = await compile(broken);

    expect(output).not.toBe("");
    expect(output).toContain("verbatra-types.d.ts");
  }, 180_000);

  it.each(TERMINATORS)(
    "calls a header with the escape undone stale rather than current for %s",
    async (_label, marker, escaped) => {
      const { dir, declaration } = await generateWith(marker);
      const broken = declaration.replace(escaped, marker);
      await writeFile(join(dir, DEFAULT_TYPES_PATH), broken, "utf8");

      const config = baseConfig({ files: { pattern: `loc${marker}ales/{locale}.json` } });
      const checked = await generateTypes({ config, cwd: dir, check: true });

      expect(declaration).toContain(escaped);
      expect(broken).not.toBe(declaration);
      expect(checked).toMatchObject({ stale: true, written: false });
      expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(broken);
    },
  );

  it("calls a second header line stale and replaces it on the next run", async () => {
    const { dir, declaration } = await generateWith("\n");
    await writeFile(
      join(dir, DEFAULT_TYPES_PATH),
      declaration.replace(
        "// Re-run",
        "ales/en.json (i18next-json). Do not edit by hand.\n// Re-run",
      ),
      "utf8",
    );
    const config = baseConfig({ files: { pattern: "loc\nales/{locale}.json" } });

    const checked = await generateTypes({ config, cwd: dir, check: true });
    const rerun = await generateTypes({ config, cwd: dir });

    expect(checked).toMatchObject({ stale: true, written: false });
    expect(rerun.written).toBe(true);
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(declaration);
  });
});
