import { lstat, mkdir, readdir, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { CACHE_FILE_NAME } from "../cache/translation-memory.js";
import { CONFIG_SEARCH_PLACES } from "../config/load-config.js";
import { defaultFs } from "../fs.js";
import { LOCK_FILE_NAME } from "../lock/lock-file.js";
import { baseConfig, makeTempDir, readTextFile } from "../test-support.js";
import { generateTypes } from "./generate-types.js";

const PROTECTED_MARKER = "the bytes that were here before the run\n";

async function seed(): Promise<string> {
  const dir = await makeTempDir();
  await mkdir(join(dir, "locales"), { recursive: true });
  await writeFile(join(dir, "locales", "en.json"), '{\n  "title": "Verbatra"\n}\n', "utf8");
  await writeFile(join(dir, "locales", "de.json"), PROTECTED_MARKER, "utf8");
  for (const name of [LOCK_FILE_NAME, CACHE_FILE_NAME, ...CONFIG_SEARCH_PLACES]) {
    await writeFile(join(dir, name), PROTECTED_MARKER, "utf8");
  }
  return dir;
}

async function refusal(dir: string, out: string): Promise<string | undefined> {
  try {
    await generateTypes({ config: baseConfig(), cwd: dir, out });
    return undefined;
  } catch (error) {
    return (error as { code?: string }).code;
  }
}

const RESERVED_NAMES: readonly string[] = [
  LOCK_FILE_NAME,
  CACHE_FILE_NAME,
  ...CONFIG_SEARCH_PLACES,
  "locales/en.json",
  "locales/de.json",
];

describe("every reserved target, named exactly", () => {
  it.each(RESERVED_NAMES)("refuses %s and leaves its bytes untouched", async (name) => {
    const dir = await seed();

    expect(await refusal(dir, name)).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, name))).not.toContain("Generated by verbatra");
  });
});

describe("every reserved target, reached by a path that is not its plain name", () => {
  const detours = (name: string): readonly string[] => [
    `./${name}`,
    `sub/../${name}`,
    `./sub/.././${name}`,
    `sub/nested/../../${name}`,
  ];

  it.each(RESERVED_NAMES.flatMap((name) => detours(name).map((out) => [name, out] as const)))(
    "refuses %s spelled as %s",
    async (name, out) => {
      const dir = await seed();

      expect(await refusal(dir, out)).toBe("TYPES_OUTPUT_CONFLICT");
      expect(await readTextFile(join(dir, name))).not.toContain("Generated by verbatra");
    },
  );

  it("refuses a reserved target reached by climbing back in from a subdirectory", async () => {
    const dir = await seed();
    await mkdir(join(dir, "generated"), { recursive: true });

    expect(await refusal(dir, "generated/../verbatra.config.ts")).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, "verbatra.config.ts"))).toBe(PROTECTED_MARKER);
  });
});

describe("a reserved target spelled in a different case", () => {
  it.each(["Verbatra.Config.ts", ".VerbatraRc.ts", "VERBATRA.CONFIG.TS", "Verbatra.Lock.json"])(
    "refuses %s, whose spelling differs from a reserved name only in case",
    async (out) => {
      const dir = await seed();

      expect(await refusal(dir, out)).toBe("TYPES_OUTPUT_CONFLICT");
      expect(await readTextFile(join(dir, "verbatra.config.ts"))).toBe(PROTECTED_MARKER);
    },
  );

  it("still accepts a TypeScript extension spelled in upper case, which claims nothing reserved", async () => {
    const dir = await seed();

    expect(await refusal(dir, "MESSAGES.D.TS")).toBe(undefined);
  });
});

describe("a symbolic link aimed at a reserved target", () => {
  it("is refused by the path guard once the link is resolved", async () => {
    const dir = await seed();
    await symlink(join(dir, "verbatra.config.ts"), join(dir, "sneaky.d.ts"));

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "sneaky.d.ts" }),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining(
        "resolves to a file verbatra loads its configuration from through a symbolic link.",
      ),
    });
    expect(await readTextFile(join(dir, "verbatra.config.ts"))).toBe(PROTECTED_MARKER);
    expect((await lstat(join(dir, "sneaky.d.ts"))).isSymbolicLink()).toBe(true);
  });

  it("is still refused by the header check through a file-system port without realpath", async () => {
    const dir = await seed();
    await symlink(join(dir, "verbatra.config.ts"), join(dir, "sneaky.d.ts"));
    const { realpath: _realpath, ...withoutRealpath } = defaultFs;

    await expect(
      generateTypes(
        { config: baseConfig(), cwd: dir, out: "sneaky.d.ts" },
        { fs: withoutRealpath },
      ),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining("was not generated by verbatra"),
    });
    expect(await readTextFile(join(dir, "verbatra.config.ts"))).toBe(PROTECTED_MARKER);
  });

  it("leaves the lock file intact when the link aims at it", async () => {
    const dir = await seed();
    await symlink(join(dir, LOCK_FILE_NAME), join(dir, "linked.d.ts"));

    expect(await refusal(dir, "linked.d.ts")).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, LOCK_FILE_NAME))).toBe(PROTECTED_MARKER);
  });
});

describe("the positive set the guard must still let through", () => {
  it.each([
    "messages.ts",
    "messages.d.ts",
    "messages.mts",
    "messages.d.mts",
    "messages.cts",
    "messages.d.cts",
    "src/generated/messages.d.ts",
    "sub/../messages.d.ts",
  ])("writes to %s", async (out) => {
    const dir = await seed();

    const result = await generateTypes({ config: baseConfig(), cwd: dir, out });

    expect(await readTextFile(result.path)).toContain("Generated by verbatra");
  });

  it.each(["messages.tsx", "messages.json", "messages.txt", "messages.ts.bak", "messages"])(
    "refuses %s, which is not a TypeScript file",
    async (out) => {
      const dir = await seed();

      expect(await refusal(dir, out)).toBe("TYPES_OUTPUT_CONFLICT");
    },
  );
});

describe("an output path that reaches through a symbolic link", () => {
  it("refuses a linked directory pointing into the locales and leaves the locale file untouched", async () => {
    const dir = await seed();
    await symlink(join(dir, "locales"), join(dir, "linked"), "dir");

    await writeFile(join(dir, "locales", "de.ts"), PROTECTED_MARKER, "utf8");
    const config = baseConfig({ files: { pattern: "locales/{locale}.ts" } });

    await expect(generateTypes({ config, cwd: dir, out: "linked/de.ts" })).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining(
        'resolves to the locale file for "de" through a symbolic link.',
      ),
    });
    expect(await readTextFile(join(dir, "locales", "de.ts"))).toBe(PROTECTED_MARKER);
  });

  it("refuses a linked file ending in .ts that points at the locale file", async () => {
    const dir = await seed();
    await symlink(join(dir, "locales", "de.json"), join(dir, "types.d.ts"), "file");

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "types.d.ts" }),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining(
        'resolves to the locale file for "de" through a symbolic link.',
      ),
    });
    expect(await readTextFile(join(dir, "locales", "de.json"))).toBe(PROTECTED_MARKER);
  });

  it("refuses a linked directory pointing outside the working directory and writes nothing there", async () => {
    const dir = await seed();
    const outside = await makeTempDir();
    await symlink(outside, join(dir, "away"), "dir");

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "away/types.d.ts" }),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining(
        "resolves outside the working directory through a symbolic link.",
      ),
    });
    expect(await readdir(outside)).toEqual([]);
  });
});

describe("an output path naming the working directory itself", () => {
  it("refuses a plain path that resolves to it", async () => {
    const dir = await seed();

    await expect(generateTypes({ config: baseConfig(), cwd: dir, out: "." })).rejects.toMatchObject(
      {
        code: "TYPES_OUTPUT_CONFLICT",
        message: expect.stringContaining("names the working directory itself."),
      },
    );
  });

  it("refuses a link that resolves to it with the same reason", async () => {
    const dir = await seed();
    await symlink(dir, join(dir, "here.d.ts"), "dir");

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, out: "here.d.ts" }),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining("names the working directory itself."),
    });
  });
});
