import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { defaultFs, type SdkFs } from "../fs.js";
import { baseConfig, makeTempDir, readTextFile, writeJsonFile } from "../test-support.js";
import { DEFAULT_TYPES_PATH, generateTypes } from "./generate-types.js";

const USER_CODE = "export const app = 1;\n";

async function seed(): Promise<string> {
  const dir = await makeTempDir();
  await mkdir(join(dir, "locales"), { recursive: true });
  await writeJsonFile(join(dir, "locales", "en.json"), { title: "Verbatra" });
  return dir;
}

async function failure(run: Promise<unknown>): Promise<{ code?: string; message?: string }> {
  try {
    await run;
  } catch (error) {
    return error as { code?: string; message?: string };
  }
  return {};
}

describe("the config file the run actually loaded", () => {
  it("is refused as the output path when it was named explicitly", async () => {
    const dir = await seed();
    await mkdir(join(dir, "config"), { recursive: true });
    await writeFile(join(dir, "config", "custom.ts"), USER_CODE, "utf8");

    const refused = await failure(
      generateTypes({
        config: baseConfig(),
        cwd: dir,
        configPath: "config/custom.ts",
        out: "config/custom.ts",
      }),
    );

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(refused.message).toContain("the configuration file this run loaded");
    expect(await readTextFile(join(dir, "config", "custom.ts"))).toBe(USER_CODE);
  });

  it("is refused with a hint to pick another path, not to pass a relative one", async () => {
    const dir = await seed();

    const refused = await failure(
      generateTypes({
        config: baseConfig(),
        cwd: dir,
        configPath: "config/custom.ts",
        out: "config/custom.ts",
      }),
    );

    expect(refused.message).toContain("Choose an output path other than the config file");
    expect(refused.message).not.toContain("Pass a relative path");
  });

  it("is refused when named by an absolute path, spelled in a different case", async () => {
    const dir = await seed();

    const refused = await failure(
      generateTypes({
        config: baseConfig(),
        cwd: dir,
        configPath: join(dir, "config", "custom.ts"),
        out: "Config/Custom.ts",
      }),
    );

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(refused.message).toContain("the configuration file this run loaded");
  });

  it("does not stand in the way of a different output path", async () => {
    const dir = await seed();

    const result = await generateTypes({
      config: baseConfig(),
      cwd: dir,
      configPath: "config/custom.ts",
    });

    expect(result.written).toBe(true);
  });
});

describe("an existing file at the output path", () => {
  it("is left untouched and refused when verbatra did not generate it", async () => {
    const dir = await seed();
    await mkdir(join(dir, "src"), { recursive: true });
    await writeFile(join(dir, "src", "app.ts"), USER_CODE, "utf8");

    const refused = await failure(
      generateTypes({ config: baseConfig(), cwd: dir, out: "src/app.ts" }),
    );

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(refused.message).toContain("was not generated by verbatra");
    expect(await readTextFile(join(dir, "src", "app.ts"))).toBe(USER_CODE);
  });

  it("is refused when it is empty, because it does not begin with the generated header", async () => {
    const dir = await seed();
    await writeFile(join(dir, DEFAULT_TYPES_PATH), "", "utf8");

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe("");
  });

  it("is refused when the generated header appears only further down", async () => {
    const dir = await seed();
    await generateTypes({ config: baseConfig(), cwd: dir });
    const generated = await readTextFile(join(dir, DEFAULT_TYPES_PATH));
    const edited = `${USER_CODE}${generated}`;
    await writeFile(join(dir, DEFAULT_TYPES_PATH), edited, "utf8");

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(edited);
  });

  it("is refused when it is too large to compare and was not generated by verbatra", async () => {
    const dir = await seed();
    const large = `${USER_CODE}${"// padding\n".repeat(2000)}`;
    await writeFile(join(dir, DEFAULT_TYPES_PATH), large, "utf8");

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(large);
  });

  it("is refused when it is too large even for the header check", async () => {
    const dir = await seed();
    const huge = `// Generated by verbatra from x (y). Do not edit by hand.\n${"x".repeat(17 * 1024 * 1024)}`;
    await writeFile(join(dir, DEFAULT_TYPES_PATH), huge, "utf8");

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
  });

  it("is refused as too large to verify, not as foreign, when even the header check cannot read it", async () => {
    const dir = await seed();
    const outputPath = join(dir, DEFAULT_TYPES_PATH);
    await writeFile(outputPath, USER_CODE, "utf8");
    const fs: SdkFs = {
      ...defaultFs,
      readFileBounded: async (path, maxBytes) =>
        path === outputPath ? { kind: "too-large" } : defaultFs.readFileBounded(path, maxBytes),
    };

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }, { fs }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(refused.message).toContain("too large to verify");
    expect(refused.message).not.toContain("was not generated by verbatra");
    expect(await readTextFile(outputPath)).toBe(USER_CODE);
  });

  it.each([
    ["a byte order mark", "\uFEFF"],
    ["a leading blank line", "\n"],
    ["leading CRLF blank lines", "\r\n\r\n"],
    ["a byte order mark and a blank line", "\uFEFF\n"],
  ])("is replaced when the generated header follows %s", async (_label, prefix) => {
    const dir = await seed();
    await writeFile(
      join(dir, DEFAULT_TYPES_PATH),
      `${prefix}// Generated by verbatra from locales/en.json (i18next-json). Do not edit by hand.\nstale\n`,
      "utf8",
    );

    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result).toMatchObject({ stale: true, written: true });
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toContain('"title"');
  });

  it("is refused when the header follows a line that is not blank", async () => {
    const dir = await seed();
    const edited =
      " \n// Generated by verbatra from locales/en.json (i18next-json). Do not edit by hand.\n";
    await writeFile(join(dir, DEFAULT_TYPES_PATH), edited, "utf8");

    const refused = await failure(generateTypes({ config: baseConfig(), cwd: dir }));

    expect(refused.code).toBe("TYPES_OUTPUT_CONFLICT");
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(edited);
  });

  it("is replaced when it begins with the header an earlier generation wrote", async () => {
    const dir = await seed();
    await writeFile(
      join(dir, DEFAULT_TYPES_PATH),
      "// Generated by verbatra from locales/en.json (i18next-json). Do not edit by hand.\nstale\n",
      "utf8",
    );

    const result = await generateTypes({ config: baseConfig(), cwd: dir });

    expect(result).toMatchObject({ stale: true, written: true });
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toContain('"title"');
  });

  it("is created when nothing is there yet", async () => {
    const dir = await seed();

    const result = await generateTypes({ config: baseConfig(), cwd: dir, out: "src/new.d.ts" });

    expect(result.written).toBe(true);
  });

  it("is only compared, never refused, in check mode", async () => {
    const dir = await seed();
    await writeFile(join(dir, DEFAULT_TYPES_PATH), USER_CODE, "utf8");

    const result = await generateTypes({ config: baseConfig(), cwd: dir, check: true });

    expect(result).toMatchObject({ stale: true, written: false, check: true });
    expect(await readTextFile(join(dir, DEFAULT_TYPES_PATH))).toBe(USER_CODE);
  });
});
