import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { baseConfig, makeTempDir } from "../test-support.js";
import {
  type GenerateTypesInput,
  generateTypes,
  TYPES_OUTPUT_REFUSALS,
  type TypesOutputRefusal,
} from "./generate-types.js";

interface RefusalScenario {
  readonly input: Omit<GenerateTypesInput, "config" | "cwd">;
  readonly why: string;
}

const REFUSAL_SCENARIOS: Readonly<Record<TypesOutputRefusal, RefusalScenario>> = {
  "names-no-file": { input: { out: " " }, why: "names no file." },
  absolute: { input: { out: "/tmp/verbatra-types.d.ts" }, why: "is absolute." },
  "outside-working-directory": {
    input: { out: "../verbatra-types.d.ts" },
    why: "is not inside the working directory.",
  },
  "not-typescript": { input: { out: "types.txt" }, why: "is not a TypeScript file" },
  "locale-file": { input: { out: "locales/en.json" }, why: 'is the locale file for "en".' },
  "lock-file": { input: { out: "verbatra.lock.json" }, why: "is the lock file" },
  "translation-memory-cache": {
    input: { out: "verbatra.cache.json" },
    why: "is the translation-memory cache.",
  },
  "config-search-place": {
    input: { out: "verbatra.config.ts" },
    why: "is a file verbatra loads its configuration from.",
  },
  "loaded-config": {
    input: { out: "config/custom.ts", configPath: "config/custom.ts" },
    why: "is the configuration file this run loaded.",
  },
  "unverified-existing-file": {
    input: { out: "src/app.ts" },
    why: "already holds a file that was not generated by verbatra",
  },
};

async function seed(): Promise<string> {
  const dir = await makeTempDir();
  await mkdir(join(dir, "locales"), { recursive: true });
  await mkdir(join(dir, "src"), { recursive: true });
  await writeFile(join(dir, "locales", "en.json"), '{\n  "title": "Verbatra"\n}\n', "utf8");
  await writeFile(join(dir, "src", "app.ts"), "export const app = 1;\n", "utf8");
  return dir;
}

describe("every refusal the output guard declares", () => {
  it.each(TYPES_OUTPUT_REFUSALS)("is reachable: %s", async (refusal) => {
    const dir = await seed();
    const scenario = REFUSAL_SCENARIOS[refusal];

    await expect(
      generateTypes({ config: baseConfig(), cwd: dir, ...scenario.input }),
    ).rejects.toMatchObject({
      code: "TYPES_OUTPUT_CONFLICT",
      message: expect.stringContaining(scenario.why),
    });
  });
});
