import type { FormatId } from "@verbatra/core";
import type { MessageArguments, MessageArgumentType } from "./message-arguments.js";

/** One catalog key as it is about to be declared, with the arguments its message takes. */
export interface DeclaredMessage {
  /** The key exactly as the adapter produced it, already flattened and never re-split. */
  readonly key: string;
  /** How the message takes its arguments. */
  readonly arguments: MessageArguments;
  /** Whether the adapter marked this entry as carrying plural forms. */
  readonly isPlural: boolean;
}

/** Everything the declaration file is rendered from. */
export interface TypesDeclarationInput {
  /** The source catalog the keys came from, relative to the run's working directory. */
  readonly sourcePath: string;
  /** The format the catalog was read with. */
  readonly format: FormatId;
  /** The keys to declare, in the order they appear in the source catalog. */
  readonly messages: readonly DeclaredMessage[];
}

const PREAMBLE = [
  "/** An argument whose type the source catalog does not record. */",
  "export type VerbatraArgument = string | number;",
  "",
  "/** The arguments of a message that takes none: passing any argument is a type error. */",
  "export type VerbatraNoArguments = Record<string, never>;",
  "",
  "/**",
  " * The arguments of a message verbatra could not analyse, so nothing is claimed about them.",
  " * Every key carrying this type is listed by `verbatra types` when it generates this file.",
  " */",
  "export type VerbatraUnknownArguments = Record<string, VerbatraArgument>;",
];

const TRAILER = [
  "/** Every key in the source catalog. */",
  "export type VerbatraMessageKey = keyof VerbatraMessages;",
  "",
  "/** The arguments the message at `Key` takes. */",
  "export type VerbatraMessageArguments<Key extends VerbatraMessageKey> =",
  "  VerbatraMessages[Key];",
];

function quote(value: string): string {
  return JSON.stringify(value);
}

function typeExpression(type: MessageArgumentType): string {
  if (type === "unknown") {
    return "VerbatraArgument";
  }
  return type;
}

function argumentsExpression(argumentsTaken: MessageArguments): string {
  if (argumentsTaken.style === "none") {
    return "VerbatraNoArguments";
  }
  if (argumentsTaken.style === "unresolved") {
    return "VerbatraUnknownArguments";
  }
  if (argumentsTaken.style === "positional") {
    return `readonly [${argumentsTaken.positional.map(typeExpression).join(", ")}]`;
  }
  const fields = argumentsTaken.named.map(
    (argument) => `readonly ${quote(argument.name)}: ${typeExpression(argument.type)}`,
  );
  return `{ ${fields.join("; ")} }`;
}

function messagesInterface(messages: readonly DeclaredMessage[]): readonly string[] {
  if (messages.length === 0) {
    return ["export interface VerbatraMessages {}"];
  }
  return [
    "export interface VerbatraMessages {",
    ...messages.map(
      (message) => `  ${quote(message.key)}: ${argumentsExpression(message.arguments)};`,
    ),
    "}",
  ];
}

function pluralKeyUnion(messages: readonly DeclaredMessage[]): string {
  const plural = messages
    .filter((message) => message.isPlural)
    .map((message) => quote(message.key));
  return plural.length === 0 ? "never" : plural.join(" | ");
}

/**
 * Render the declaration file for one source catalog. Pure string building over the messages it is
 * given, so the same input always renders the same bytes.
 *
 * @param input - The source catalog's path and format, and the keys to declare in document order.
 * @returns The complete declaration file, ending in a single newline.
 */
export function renderTypesDeclaration(input: TypesDeclarationInput): string {
  const lines = [
    `// Generated by verbatra from ${input.sourcePath} (${input.format}). Do not edit by hand.`,
    "// Re-run `verbatra types` after the source catalog changes.",
    "",
    ...PREAMBLE,
    "",
    "/** Every key in the source catalog, mapped to the arguments its message takes. */",
    ...messagesInterface(input.messages),
    "",
    ...TRAILER,
    "",
    "/** The keys the source catalog marks as carrying plural forms. */",
    `export type VerbatraPluralMessageKey = ${pluralKeyUnion(input.messages)};`,
  ];
  return `${lines.join("\n")}\n`;
}
