import { describe, expect, it } from "vitest";
import { declaredMembers } from "../test-support.js";
import type { DeclaredMessage } from "./types-declaration.js";
import { renderTypesDeclaration } from "./types-declaration.js";

function message(overrides: Partial<DeclaredMessage> & { key: string }): DeclaredMessage {
  return { arguments: { style: "none" }, isPlural: false, ...overrides };
}

function render(messages: readonly DeclaredMessage[]): string {
  return renderTypesDeclaration({
    sourcePath: "locales/en.json",
    format: "i18next-json",
    messages,
  });
}

describe("renderTypesDeclaration: the whole file", () => {
  it("emits a header, the shared argument types, the message map, and its aliases", () => {
    const declaration = render([
      message({ key: "app.title" }),
      message({
        key: "app.greeting",
        arguments: { style: "named", named: [{ name: "name", type: "unknown" }] },
      }),
    ]);

    expect(declaration).toBe(
      [
        "// Generated by verbatra from locales/en.json (i18next-json). Do not edit by hand.",
        "// Re-run `verbatra types` after the source catalog changes.",
        "",
        "/** An argument whose type the source catalog does not record. */",
        "export type VerbatraArgument = string | number;",
        "",
        "/** The arguments of a message that takes none: passing any argument is a type error. */",
        "export type VerbatraNoArguments = Record<string, never>;",
        "",
        "/**",
        " * The arguments of a message verbatra could not analyse, so nothing is claimed about them.",
        " * Every key carrying this type is listed by `verbatra types` when it generates this file.",
        " */",
        "export type VerbatraUnknownArguments = Record<string, VerbatraArgument>;",
        "",
        "/** Every key in the source catalog, mapped to the arguments its message takes. */",
        "export interface VerbatraMessages {",
        '  "app.title": VerbatraNoArguments;',
        '  "app.greeting": { readonly "name": VerbatraArgument };',
        "}",
        "",
        "/** Every key in the source catalog. */",
        "export type VerbatraMessageKey = keyof VerbatraMessages;",
        "",
        "/** The arguments the message at `Key` takes. */",
        "export type VerbatraMessageArguments<Key extends VerbatraMessageKey> =",
        "  VerbatraMessages[Key];",
        "",
        "/** The keys the source catalog marks as carrying plural forms. */",
        "export type VerbatraPluralMessageKey = never;",
        "",
      ].join("\n"),
    );
  });

  it("ends with exactly one trailing newline", () => {
    const declaration = render([message({ key: "a" })]);

    expect(declaration.endsWith(";\n")).toBe(true);
    expect(declaration.endsWith(";\n\n")).toBe(false);
  });

  it("names the source file and format it was generated from", () => {
    const declaration = renderTypesDeclaration({
      sourcePath: "messages/en.json",
      format: "next-intl-json",
      messages: [],
    });

    expect(declaration).toContain(
      "// Generated by verbatra from messages/en.json (next-intl-json).",
    );
  });

  it("keeps the header on one line when the source path carries a line break", () => {
    const declaration = renderTypesDeclaration({
      sourcePath: "locales/\nen.json",
      format: "i18next-json",
      messages: [],
    });
    const [header] = declaration.split("\n");

    expect(header).toBe(
      "// Generated by verbatra from locales/\\nen.json (i18next-json). Do not edit by hand.",
    );
    expect(declaration.split("\n").filter((line) => line.includes("en.json"))).toHaveLength(1);
  });

  it("escapes every line terminator a path could smuggle into the header", () => {
    for (const [raw, escaped] of [
      ["a\rb", "a\\rb"],
      ["a\nb", "a\\nb"],
      ["a\u2028b", "a\\u2028b"],
      ["a\u2029b", "a\\u2029b"],
    ]) {
      const declaration = renderTypesDeclaration({
        sourcePath: raw ?? "",
        format: "i18next-json",
        messages: [],
      });

      expect(declaration.split("\n")[0]).toContain(escaped ?? "");
    }
  });

  it("emits an empty map for a catalog with no keys", () => {
    expect(render([])).toContain("export interface VerbatraMessages {}\n");
  });
});

describe("renderTypesDeclaration: argument shapes", () => {
  it("gives a message with no placeholders a shape that accepts no argument", () => {
    expect(declaredMembers(render([message({ key: "plain" })]))).toEqual([
      '  "plain": VerbatraNoArguments;',
    ]);
  });

  it("types a named argument the catalog annotated as a number", () => {
    const declaration = render([
      message({
        key: "cart.items",
        arguments: { style: "named", named: [{ name: "count", type: "number" }] },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual(['  "cart.items": { readonly "count": number };']);
  });

  it("types a named argument the catalog annotated as text", () => {
    const declaration = render([
      message({
        key: "who",
        arguments: { style: "named", named: [{ name: "who", type: "string" }] },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual(['  "who": { readonly "who": string };']);
  });

  it("types a date argument as a Date or a timestamp", () => {
    const declaration = render([
      message({
        key: "due",
        arguments: { style: "named", named: [{ name: "d", type: "date" }] },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual(['  "due": { readonly "d": Date | number };']);
  });

  it("keeps several named arguments in the order they were described", () => {
    const declaration = render([
      message({
        key: "both",
        arguments: {
          style: "named",
          named: [
            { name: "b", type: "unknown" },
            { name: "a", type: "number" },
          ],
        },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual([
      '  "both": { readonly "b": VerbatraArgument; readonly "a": number };',
    ]);
  });

  it("marks an argument only some branches use as an optional member", () => {
    const declaration = render([
      message({
        key: "invite",
        arguments: {
          style: "named",
          named: [
            { name: "gender", type: "unknown" },
            { name: "name", type: "unknown", optional: true },
          ],
        },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual([
      '  "invite": { readonly "gender": VerbatraArgument; readonly "name"?: VerbatraArgument };',
    ]);
  });

  it("emits a readonly tuple for a message whose arguments are positional", () => {
    const declaration = render([
      message({
        key: "legacy",
        arguments: { style: "positional", positional: ["unknown", "number"] },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual([
      '  "legacy": readonly [VerbatraArgument, number];',
    ]);
  });

  it("emits an empty tuple rather than a no-argument shape for an empty position list", () => {
    const declaration = render([
      message({ key: "edge", arguments: { style: "positional", positional: [] } }),
    ]);

    expect(declaredMembers(declaration)).toEqual(['  "edge": readonly [];']);
  });

  it("marks a message whose arguments could not be determined", () => {
    const declaration = render([
      message({
        key: "broken",
        arguments: { style: "unresolved", reason: "invalid-message-syntax" },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual(['  "broken": VerbatraUnknownArguments;']);
  });
});

describe("renderTypesDeclaration: keys that are not valid identifiers", () => {
  it("quotes a key that already carries a dot, without re-splitting it", () => {
    expect(declaredMembers(render([message({ key: "a.b.c" })]))).toEqual([
      '  "a.b.c": VerbatraNoArguments;',
    ]);
  });

  it("quotes a key that is a reserved word", () => {
    expect(declaredMembers(render([message({ key: "class" })]))).toEqual([
      '  "class": VerbatraNoArguments;',
    ]);
  });

  it("quotes a key that starts with a digit", () => {
    expect(declaredMembers(render([message({ key: "1st" })]))).toEqual([
      '  "1st": VerbatraNoArguments;',
    ]);
  });

  it("emits the empty key rather than dropping it", () => {
    expect(declaredMembers(render([message({ key: "" })]))).toEqual(['  "": VerbatraNoArguments;']);
  });

  it("escapes a key containing a double quote", () => {
    expect(declaredMembers(render([message({ key: 'say "hi"' })]))).toEqual([
      '  "say \\"hi\\"": VerbatraNoArguments;',
    ]);
  });

  it("escapes a key containing a backslash", () => {
    expect(declaredMembers(render([message({ key: "a\\b" })]))).toEqual([
      '  "a\\\\b": VerbatraNoArguments;',
    ]);
  });

  it("escapes a key containing a newline", () => {
    expect(declaredMembers(render([message({ key: "a\nb" })]))).toEqual([
      '  "a\\nb": VerbatraNoArguments;',
    ]);
  });

  it("escapes an argument name that is not a valid identifier", () => {
    const declaration = render([
      message({
        key: "odd",
        arguments: { style: "named", named: [{ name: 'we"ird', type: "unknown" }] },
      }),
    ]);

    expect(declaredMembers(declaration)).toEqual([
      '  "odd": { readonly "we\\"ird": VerbatraArgument };',
    ]);
  });
});

describe("renderTypesDeclaration: plural keys", () => {
  it("lists every key the catalog marked plural, without collapsing its siblings", () => {
    const declaration = render([
      message({ key: "cart.item_one", isPlural: true }),
      message({ key: "cart.item_other", isPlural: true }),
      message({ key: "app.title" }),
    ]);

    expect(declaration).toContain(
      'export type VerbatraPluralMessageKey = "cart.item_one" | "cart.item_other";',
    );
    expect(declaredMembers(declaration)).toEqual([
      '  "cart.item_one": VerbatraNoArguments;',
      '  "cart.item_other": VerbatraNoArguments;',
      '  "app.title": VerbatraNoArguments;',
    ]);
  });

  it("resolves to never when the catalog marks no key plural", () => {
    expect(render([message({ key: "a" })])).toContain(
      "export type VerbatraPluralMessageKey = never;",
    );
  });
});
