import type { FormatId } from "@verbatra/core";
import type { MessageArguments, MessageArgumentType } from "./message-arguments.js";

export interface DeclaredMessage {
  readonly key: string;
  readonly arguments: MessageArguments;
  readonly isPlural: boolean;
}

export interface TypesDeclarationInput {
  readonly sourcePath: string;
  readonly format: FormatId;
  readonly messages: readonly DeclaredMessage[];
}

const PREAMBLE = [
  "/** An argument whose type the source catalog does not record. */",
  "export type VerbatraArgument = string | number;",
  "",
  "/** The arguments of a message that takes none: passing any argument is a type error. */",
  "export type VerbatraNoArguments = Record<string, never>;",
  "",
  "/**",
  " * The arguments of a message verbatra could not analyse, so nothing is claimed about them.",
  " * Every key carrying this type is listed by `verbatra types` when it generates this file.",
  " */",
  "export type VerbatraUnknownArguments = Record<string, VerbatraArgument>;",
];

const TRAILER = [
  "/** Every key in the source catalog. */",
  "export type VerbatraMessageKey = keyof VerbatraMessages;",
  "",
  "/** The arguments the message at `Key` takes. */",
  "export type VerbatraMessageArguments<Key extends VerbatraMessageKey> =",
  "  VerbatraMessages[Key];",
];

const LINE_TERMINATOR = /[\r\n\u2028\u2029]/g;

const LINE_TERMINATOR_ESCAPES: Readonly<Record<string, string>> = {
  "\r": "\\r",
  "\n": "\\n",
  "\u2028": "\\u2028",
  "\u2029": "\\u2029",
};

function onOneLine(value: string): string {
  return value.replace(LINE_TERMINATOR, (match) => LINE_TERMINATOR_ESCAPES[match] ?? " ");
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function typeExpression(type: MessageArgumentType): string {
  if (type === "unknown") {
    return "VerbatraArgument";
  }
  return type;
}

function argumentsExpression(argumentsTaken: MessageArguments): string {
  if (argumentsTaken.style === "none") {
    return "VerbatraNoArguments";
  }
  if (argumentsTaken.style === "unresolved") {
    return "VerbatraUnknownArguments";
  }
  if (argumentsTaken.style === "positional") {
    return `readonly [${argumentsTaken.positional.map(typeExpression).join(", ")}]`;
  }
  const fields = argumentsTaken.named.map(
    (argument) =>
      `readonly ${quote(argument.name)}${argument.optional === true ? "?" : ""}: ${typeExpression(argument.type)}`,
  );
  return `{ ${fields.join("; ")} }`;
}

function messagesInterface(messages: readonly DeclaredMessage[]): readonly string[] {
  if (messages.length === 0) {
    return ["export interface VerbatraMessages {}"];
  }
  return [
    "export interface VerbatraMessages {",
    ...messages.map(
      (message) => `  ${quote(message.key)}: ${argumentsExpression(message.arguments)};`,
    ),
    "}",
  ];
}

function pluralKeyUnion(messages: readonly DeclaredMessage[]): string {
  const plural = messages
    .filter((message) => message.isPlural)
    .map((message) => quote(message.key));
  return plural.length === 0 ? "never" : plural.join(" | ");
}

export function renderTypesDeclaration(input: TypesDeclarationInput): string {
  const lines = [
    `// Generated by verbatra from ${onOneLine(input.sourcePath)} (${onOneLine(input.format)}). Do not edit by hand.`,
    "// Re-run `verbatra types` after the source catalog changes.",
    "",
    ...PREAMBLE,
    "",
    "/** Every key in the source catalog, mapped to the arguments its message takes. */",
    ...messagesInterface(input.messages),
    "",
    ...TRAILER,
    "",
    "/** The keys the source catalog marks as carrying plural forms. */",
    `export type VerbatraPluralMessageKey = ${pluralKeyUnion(input.messages)};`,
  ];
  return `${lines.join("\n")}\n`;
}
