import type { LocaleResource, TranslationEntry } from "@verbatra/core";
import { describe, expect, it } from "vitest";
import { AdapterError } from "../errors.js";
import { createMemoryAdapterFs, type MemoryAdapterFs } from "../test-support.js";
import { createResxAdapter } from "./resx-adapter.js";

const DESIGNER_FIXTURE = `<?xml version="1.0" encoding="utf-8"?>
<root>
  <!-- Generated by the designer, do not edit by hand -->
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:element name="root" msdata:IsDataSet="true"/>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <assembly alias="System.Drawing" name="System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"/>
  <metadata name="statusStrip.TrayLocation" type="System.Drawing.Point, System.Drawing" mimetype="application/x-microsoft.net.object.bytearray.base64">
    <value>17, 17</value>
  </metadata>
  <data name="Greeting" xml:space="preserve">
    <value>Hello {0}</value>
  </data>
</root>
`;

function setup(files: Record<string, string> = {}): {
  readonly adapter: ReturnType<typeof createResxAdapter>;
  readonly fs: MemoryAdapterFs;
} {
  const fs = createMemoryAdapterFs(files);
  return { adapter: createResxAdapter(fs), fs };
}

function entry(key: string, value: string): TranslationEntry {
  return { key, namespace: "Resources", value, placeholders: [], isPlural: false };
}

function resource(entries: readonly TranslationEntry[]): LocaleResource {
  return {
    locale: "de",
    namespace: "Resources",
    format: "resx",
    entries: new Map(entries.map((item) => [item.key, item])),
  };
}

async function readModifyWrite(
  source: string,
  mutate: (entries: Map<string, TranslationEntry>) => void = (): void => {},
): Promise<string> {
  const { adapter, fs } = setup({ "Resources.resx": source });
  const { resource: read } = await adapter.read("Resources.resx", "en");
  const entries = new Map(read.entries);
  mutate(entries);
  await adapter.write({ ...read, entries }, "Resources.resx");
  return fs.files.get("Resources.resx") ?? "";
}

describe("createResxAdapter preserves content it does not own", () => {
  it("leaves a designer preamble of schema, comment, assembly, and metadata byte-identical", async () => {
    expect(await readModifyWrite(DESIGNER_FIXTURE)).toBe(DESIGNER_FIXTURE);
  });

  it("keeps the designer preamble intact while rewriting the one translatable value", async () => {
    const written = await readModifyWrite(DESIGNER_FIXTURE, (entries) => {
      entries.set("Greeting", entry("Greeting", "Hallo {0}"));
    });
    expect(written).toContain('<xsd:element name="root" msdata:IsDataSet="true"/>');
    expect(written).toContain('<assembly alias="System.Drawing"');
    expect(written).toContain('<metadata name="statusStrip.TrayLocation"');
    expect(written).toContain("<!-- Generated by the designer, do not edit by hand -->");
    expect(written).toContain("<value>Hallo {0}</value>");
  });

  it("round-trips a header-only document that holds no data element at all", async () => {
    const source =
      '<?xml version="1.0" encoding="utf-8"?>\n<root>\n  <resheader name="version">\n    <value>2.0</value>\n  </resheader>\n</root>\n';
    const { adapter, fs } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.size).toBe(0);
    await adapter.write(read, "Resources.resx");
    expect(fs.files.get("Resources.resx")).toBe(source);
  });

  it("appends into a document that has no data element without disturbing its headers", async () => {
    const source =
      '<?xml version="1.0" encoding="utf-8"?>\n<root>\n  <resheader name="version">\n    <value>2.0</value>\n  </resheader>\n</root>\n';
    const { adapter, fs } = setup({ "Resources.resx": source });
    await adapter.write(resource([entry("Greeting", "Hallo")]), "Resources.resx");
    const written = fs.files.get("Resources.resx") ?? "";
    expect(written).toContain('<resheader name="version">\n    <value>2.0</value>\n  </resheader>');
    expect(written).toContain('<data name="Greeting" xml:space="preserve"><value>Hallo</value>');
  });

  it("preserves a CDATA value untouched and never offers it for translation", async () => {
    const source =
      '<root>\n  <data name="Snippet" xml:space="preserve">\n    <value><![CDATA[raw <b>markup</b> here]]></value>\n  </data>\n</root>\n';
    const { adapter, fs } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.has("Snippet")).toBe(false);
    await adapter.write(resource([entry("Other", "x")]), "Resources.resx");
    expect(fs.files.get("Resources.resx")).toContain("<![CDATA[raw <b>markup</b> here]]>");
  });

  it("keeps an entry whose value needs escaping semantically identical across a round-trip", async () => {
    const source =
      '<root>\n  <data name="A" xml:space="preserve">\n    <value>a &lt; b &gt; c &amp; d</value>\n  </data>\n</root>\n';
    const { adapter } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.get("A")?.value).toBe("a < b > c & d");
    expect(await readModifyWrite(source)).toBe(source);
  });

  it("re-escapes a quote, an apostrophe, and a numeric reference to their shortest legal form", async () => {
    const source =
      '<root>\n  <data name="A" xml:space="preserve">\n    <value>&quot;q&quot; &apos;s&apos; &#10;</value>\n  </data>\n</root>\n';
    const { adapter } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.get("A")?.value).toBe("\"q\" 's' \n");
    expect(await readModifyWrite(source)).toBe(
      '<root>\n  <data name="A" xml:space="preserve">\n    <value>"q" \'s\' \n</value>\n  </data>\n</root>\n',
    );
  });

  it("writes a value containing markup characters back as escaped text, not as markup", async () => {
    const { adapter, fs } = setup({
      "Resources.resx": '<root>\n  <data name="A"><value>x</value></data>\n</root>\n',
    });
    await adapter.write(resource([entry("A", '<b>bold</b> & "quoted"')]), "Resources.resx");
    const written = fs.files.get("Resources.resx") ?? "";
    expect(written).toContain('<value>&lt;b&gt;bold&lt;/b&gt; &amp; "quoted"</value>');
    const { resource: reread } = await createResxAdapter(fs).read("Resources.resx", "en");
    expect(reread.entries.get("A")?.value).toBe('<b>bold</b> & "quoted"');
  });

  it("expands a self-closing empty value into an open and close pair holding the empty string", async () => {
    const source =
      '<root>\n  <data name="A" xml:space="preserve">\n    <value/>\n  </data>\n</root>\n';
    const { adapter } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.get("A")?.value).toBe("");
    expect(await readModifyWrite(source)).toBe(
      '<root>\n  <data name="A" xml:space="preserve">\n    <value></value>\n  </data>\n</root>\n',
    );
  });

  it("keeps a CRLF document on CRLF throughout, not just at the final newline", async () => {
    const source =
      '<?xml version="1.0" encoding="utf-8"?>\r\n<root>\r\n  <data name="A" xml:space="preserve">\r\n    <value>x</value>\r\n  </data>\r\n</root>\r\n';
    expect(await readModifyWrite(source)).toBe(source);
  });

  it("keeps a CRLF document on CRLF when a value is rewritten and a key is added", async () => {
    const source =
      '<?xml version="1.0" encoding="utf-8"?>\r\n<root>\r\n  <data name="A" xml:space="preserve">\r\n    <value>x</value>\r\n  </data>\r\n</root>\r\n';
    const written = await readModifyWrite(source, (entries) => {
      entries.set("A", entry("A", "y"));
      entries.set("B", entry("B", "z"));
    });
    expect(written.includes("\n")).toBe(true);
    expect(written.replaceAll("\r\n", "")).not.toContain("\n");
    expect(written).toContain("<value>y</value>");
    expect(written).toContain('<data name="B" xml:space="preserve"><value>z</value></data>');
  });

  it("never doubles a carriage return when a translated value already carries CRLF", async () => {
    const source =
      '<?xml version="1.0" encoding="utf-8"?>\r\n<root>\r\n  <data name="A" xml:space="preserve">\r\n    <value>x</value>\r\n  </data>\r\n</root>\r\n';
    const written = await readModifyWrite(source, (entries) => {
      entries.set("A", entry("A", "line1\r\nline2"));
    });
    expect(written).not.toContain("\r\r");
    const { adapter, fs } = setup({ "Resources.resx": written });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.get("A")?.value).toBe("line1\nline2");
    await adapter.write(read, "Resources.resx");
    expect(fs.files.get("Resources.resx")).toBe(written);
  });

  it("drops a leading byte order mark rather than writing it back", async () => {
    const source =
      '﻿<?xml version="1.0" encoding="utf-8"?>\n<root>\n  <data name="A"><value>x</value></data>\n</root>\n';
    const written = await readModifyWrite(source);
    expect(written.startsWith("﻿")).toBe(false);
    expect(written).toBe(source.slice(1));
  });

  it("collapses two data elements sharing a name onto the value the later one carried", async () => {
    const source =
      '<root>\n  <data name="A"><value>one</value></data>\n  <data name="A"><value>two</value></data>\n</root>\n';
    const { adapter } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    expect(read.entries.get("A")?.value).toBe("two");
    expect(await readModifyWrite(source)).toBe(
      '<root>\n  <data name="A"><value>two</value></data>\n  <data name="A"><value>two</value></data>\n</root>\n',
    );
  });

  it("appends to a document whose root has no closing indent text node", async () => {
    const source = '<root><data name="A"><value>x</value></data></root>';
    const { adapter, fs } = setup({ "Resources.resx": source });
    const { resource: read } = await adapter.read("Resources.resx", "en");
    const entries = new Map(read.entries);
    entries.set("B", entry("B", "y"));
    await adapter.write({ ...read, entries }, "Resources.resx");
    expect(fs.files.get("Resources.resx")).toBe(
      '<root><data name="A"><value>x</value></data>\n  <data name="B" xml:space="preserve"><value>y</value></data></root>',
    );
  });

  it("never translates or removes a designer name when no resource carries that name", async () => {
    const source =
      '<root>\n  <data name="&gt;&gt;A.Name" xml:space="preserve"><value>designerA</value></data>\n  <data name="$B.Text" xml:space="preserve"><value>designerB</value></data>\n</root>\n';
    const { adapter, fs } = setup({ "Resources.resx": source });
    await adapter.write(resource([]), "Resources.resx");
    expect(fs.files.get("Resources.resx")).toBe(source);
  });

  it("refuses the write when a resource carries a designer name, rather than dropping its value", async () => {
    const source =
      '<root>\n  <data name="&gt;&gt;A.Name" xml:space="preserve"><value>designerA</value></data>\n</root>\n';
    const { adapter, fs } = setup({ "Resources.resx": source });
    const error = await adapter
      .write(resource([entry(">>A.Name", "translated")]), "Resources.resx")
      .catch((caught: unknown) => caught);
    expect(error).toBeInstanceOf(AdapterError);
    expect(fs.files.get("Resources.resx")).toBe(source);
  });
});
